config/routes.rb
Rails.application.routes.draw do
  devise_for :my_users
  get 'home/index'
  root "home#index"
  resources :my_user
  devise_for :views
  resources :products
  resources :students
  resources :faculties
  resources :books
  resources :author
  resources :images
  resources :user001s
  resources :new_users do
    member do
      get :user_profile
      patch :update_profile
      get :change_password
      post :update_password
    end
    collection do
      post :check_password
    end
  end
  resources :food_products do
    resources :food_orders,only: [:index, :show, :edit, :update, :destroy, :new, :create]
  end
  get '/food_orders', to: 'food_orders#show_all'
  
  resources :staffs, only: [:index, :show, :destroy, :update, :edit, :new, :create] do
    collection do
      get :search
    end
  end
  resources :users, only: [:new,:create] do
    collection do
      get :user_profile
    end
  end
  resources :events, only: [:index, :show, :destroy, :update, :edit, :new, :create] do
    member do
      get :user_enrol
    end
    collection do
      get :filter
      get :add_comment
    end
  end
  resources :customers, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :most_booked_order_of_product
      get :most_cancelled_order_of_product
      get :most_sales_product_by_price
      get :most_sales_product_by_quantity
    end
  end
  resources :orders, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :search
      get :filter_data
    end
  end
  resources :shopproducts, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :display_all_products
      get :display_all_products_default
      get :search
    end
  end
  namespace :business do
    resources :buyers, only: [:index, :edit, :create] do
        get 'search', on: :collection
        get 'preview', on: :member
        delete 'delete_customer', on: :member
        patch 'update', on: :member
        get 'new', on: :collection, as: 'new'
    end
  end
  namespace :api do
    namespace :v1 do
      resources :articles do
        get 'search', on: :collection
      end
      resources :article_comments do
        get 'search', on: :collection
      end
    end
  end
  post '/books/save', to: 'books#save', as: 'save'
  post '/author/save', to: 'author#save', as: 'author_save' 
  #root "food_products#index"
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :employee_addresses, dependent: :destroy
  accepts_nested_attributes_for :employee_addresses, allow_destroy: true
  has_one_attached :document, dependent: :destroy
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  def index
    @staffs = Staff.all
  end

  def show
    @staff= Staff.find(params['id'])
  end

  def new
    @staff = Staff.new
    1.times { @staff.employee_addresses.build }
  end

  def create
    @staff=Staff.create(staff_params)
    if @staff.valid?
      redirect_to '/staffs'
    else 
      flash[:alert] = @staff.errors.full_messages
      redirect_to new_staff_path
    end
  end

  def edit
    @staff = Staff.find(params['id'])
  end

  def update
  @staff = Staff.find(params[:id])
  @staff.update(staff_params)
    if @staff.valid?
      redirect_to '/staffs'
    else 
      flash[:errors] = @staff.errors.full_messages
      redirect_to staff_path
    end
  end

  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy
    redirect_to '/staffs'
  end

  def search
    if params[:q].blank?
      flash[:errors]=""
      return
    else
      name=params[:q]
      @staffs=Staff.where(employee_name: name)
      puts @staffs
      @staffs.each do |s|
        puts s.employee_name
      end
      if @staffs.blank?
        flash[:errors] = "Data not found"
      else
        flash[:errors]=""
      end  
    end
  end

  private
  def staff_params
    params.require(:staff).permit(:employee_name,:email,:password,:gender,{hobbies:[]},:address,:mobile_number,:birth_date,:document, employee_addresses_attributes: [:house_name,:street_name,:road])
  end
end

app/views/staffs/edit.html.erb
<h1>Editing Staff Details</h1>

<%= form_with model: @staff do |form| %>
  <div>
    <%= form.label :employee_name, style: "display: block" %>
    <%= form.text_field :employee_name %>
  </div>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>
  
   <div>
      <%= form.radio_button :gender, "female" %>
      <%= form.label :female, "Female" %>
      <%= form.radio_button :gender, "male" %>
      <%= form.label :male, "Male" %>
  </div>
  <% ['dancing','singing'].each do |hobbies| %>
    <%= check_box_tag "staff[hobbies][]", hobbies, @staff.hobbies.to_s.include?(hobbies) %>
    <%= form.label :hobbies, "#{hobbies}" %>
 <% end %>
  <div>
      <%= form.label :address, style: "display: block" %>
      <%= form.text_field :address %>
  </div>
  <div>
    <%=form.fields_for :employee_addresses do |a|%>
      <%= form.label :house_name, style: "display: block" %>
      <%= a.text_field :house_name %>
      <%= form.label :street_name, style: "display: block" %>
      <%= a.text_field :street_name %>
      <%= form.label :road, style: "display: block" %>
      <%= a.text_field :road %>
    <% end %>
  </div>
  <div>
    <%= form.label :mobile_number, style: "display: block" %>
    <%= form.telephone_field :mobile_number %>
  </div>
  <div>
    <%= form.label :birth_date, style: "display: block" %>
    <%= form.date_field :birth_date %>
  </div>
  <div>
    <p><b>Document : </b></p><br/>
    <% if @staff.document.attached? %>
        <%= image_tag @staff.document, style: "width: 100px; display: block:" %>
    <% end %>
  </div>
  <div>
    <%=form.label :document %>
    <%= form.file_field :document %>
  </div>
  <div>
      <%= form.submit %>
  </div>

<%end%>

app/views/staffs/index.html.erb
<h1> Student Details </h1>
<table border=" solid 3px ">
  <tr>
  <th>Emplyee_name</th>
  <th>Email</th>
  <th>gender</th>
  <th>Hobbies</th>
  <th>address</th>
  <th>Mobile_number</th>
  <th>Birth_date</th>
  </tr>
   <% @staffs.each do |staff| %>
    <tr>
      <td><%=staff.employee_name %></td>
      <td><%=staff.email %></td>
      <td><%=staff.gender %></td>
      <td><%=staff.hobbies %></td>
      <td><%=staff.address %></td>
      <td><%=staff.mobile_number %></td>
      <td><%=staff.birth_date %></td>
      <td><%= link_to "Edit Staff", edit_staff_path(id: staff.id) %></td>
      <td><%= link_to "Show Staff", staff_path(id: staff.id) %></td>
      <td><%= button_to "Destroy Staff",staff_path(id: staff.id),
            method: 'delete' ,
            data:{ confirm: "are you sure"}%></td>
    </tr>
  <% end %>
</table>
<br/>
<%= link_to "Add a new Staff member", new_staff_path %><br/><br/>
<%= link_to "Search Employee by name", search_staffs_path %>
 

app/views/staffs/new.html.erb
<h1>Add New Staff</h1>
<% if flash[:alert] %>
  <div >
    <ul>
      <% flash[:alert].each do |error| %>
        <li style="color:red;"><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model: @staff do |form| %>
  <div>
    <%= form.label :employee_name, style: "display: block" %>
    <%= form.text_field :employee_name %>
  </div>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>
   <div>
    <%= form.radio_button :gender, "female" %>
    <%= form.label :female, "Female" %>
    <%= form.radio_button :gender, "male" %>
    <%= form.label :male, "Male" %>
  </div>
   <div>
    <%= form.check_box :hobbies,{multiple: true}, "dancing",false  %>
    <%= form.label :dancing, "Dancing" %>
    <%= form.check_box :hobbies, {multiple: true}, "singing",false %>
    <%= form.label :singing, "Singing" %>
  </div>
  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>
  <div>
    <%=form.fields_for :employee_addresses do |a|%>
    <%= form.label :house_name, style: "display: block" %>
    <%= a.text_field :house_name %>
    <%= form.label :street_name, style: "display: block" %>
    <%= a.text_field :street_name %>
    <%= form.label :road, style: "display: block" %>
    <%= a.text_field :road %>
    <% end %>
  </div>
  <div>
    <%= form.label :mobile_number, style: "display: block" %>
    <%= form.telephone_field :mobile_number %>
  </div>
  <div>
    <%= form.label :birth_date, style: "display: block" %>
    <%= form.date_field :birth_date %>
  </div>
  <div>
    <%=form.label :document %>
    <%= form.file_field :document %>
  </div>
  <div>
      <%= form.submit %>
  </div>

<%end%>

app/views/staffs/search.html.erb
<h1>Search page</h1>
<% if !flash[:errors].empty? %>
  <div >
    <ul>
      <li style="color:red;"><%= flash[:errors] %></li>
    </ul>
  </div>
<% end %>
<%= form_tag( search_staffs_path, :method => "get") do %>
  <%= label_tag(:q, "Search data by employee name:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<% if (@staffs != nil) %>
  <h1>Staff data found</h1>
  <% @staffs.each do |staff| %>
  <div >
  <p>
    <strong>Employee Name:</strong>
    <%= staff.employee_name %>
  </p>
  <p>
    <strong>email:</strong>
    <%= staff.email %>
  </p>
  <p>
    <strong>password:</strong>
    <%= staff.password %>
  </p>
  <p>
    <strong>gender:</strong>
    <%= staff.gender %>
  </p>
  <p>
    <strong>Hobbies:</strong>
    <%= staff.hobbies %>
  </p>
  <p>
    <strong>Address:</strong>
    <%= staff.address %>
  </p>
  <p>
    <strong>Mobile Number:</strong>
    <%= staff.mobile_number %>
  </p>
  <p>
    <strong>Birth Date:</strong>
    <%= staff.birth_date %>
  </p>
  </div>

  <% end %>
<% end %>
<%= link_to "Show Staff index page", staffs_path %><br/><br/>

app/views/staffs/show.html.erb
<h1>Staff</h1>
<div >
  <p>
    <strong>Emplyee Name:</strong>
    <%= @staff.employee_name %>
  </p>
  <p>
    <strong>email:</strong>
    <%= @staff.email %>
  </p>
  <p>
    <strong>password:</strong>
    <%= @staff.password %>
  </p>
  <p>
    <strong>gender:</strong>
    <%= @staff.gender %>
  </p>
  <p>
    <strong>Hobbies:</strong>
    <%= @staff.hobbies %>
  </p>
  <p>
    <strong>Address:</strong>
    <%= @staff.address %>
  </p>
  <p>
    <%@staff.employee_addresses.each do |e|%>
      <strong>House Name:</strong>
      <%= e.house_name %><br/><br/>
      <strong>Street Name:</strong>
      <%= e.street_name %><br/><br/>
      <strong>Road:</strong>
      <%= e.road %><br/>
    <% end %>
  </p>
  <p>
    <strong>Mobile Number:</strong>
    <%= @staff.mobile_number %>
  </p>
  <p>
    <strong>Birth Date:</strong>
    <%= @staff.birth_date %>
  </p>
  <p>
    <p><b>Document : </b></p><br/>
    <% if @staff.document.attached? %>
        <%= image_tag @staff.document, style: "width: 100px; display: block:" %>
    <% end %>
  </p>
</div>