config/routes.rb
Rails.application.routes.draw do
  devise_for :my_users
  get 'home/index'
  root "home#index"
  resources :my_user
  devise_for :views
  resources :products
  resources :students
  resources :faculties
  resources :books
  resources :author
  resources :images
  resources :user001s
  resources :new_users do
    member do
      get :user_profile
      patch :update_profile
      get :change_password
      post :update_password
    end
    collection do
      post :check_password
    end
  end
  resources :food_products do
    resources :food_orders,only: [:index, :show, :edit, :update, :destroy, :new, :create]
  end
  get '/food_orders', to: 'food_orders#show_all'
  
  resources :staffs, only: [:index, :show, :destroy, :update, :edit, :new, :create] do
    collection do
      get :search
    end
  end
  resources :users, only: [:new,:create] do
    collection do
      get :user_profile
    end
  end
  resources :events, only: [:index, :show, :destroy, :update, :edit, :new, :create] do
    member do
      get :user_enrol
    end
    collection do
      get :filter
      get :add_comment
    end
  end
  resources :customers, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :most_booked_order_of_product
      get :most_cancelled_order_of_product
      get :most_sales_product_by_price
      get :most_sales_product_by_quantity
    end
  end
  resources :orders, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :search
      get :filter_data
    end
  end
  resources :shopproducts, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :display_all_products
      get :display_all_products_default
      get :search
    end
  end
  namespace :business do
    resources :buyers, only: [:index, :edit, :create] do
        get 'search', on: :collection
        get 'preview', on: :member
        delete 'delete_customer', on: :member
        patch 'update', on: :member
        get 'new', on: :collection, as: 'new'
    end
  end
  namespace :api do
    namespace :v1 do
      resources :articles do
        get 'search', on: :collection
      end
      resources :article_comments do
        get 'search', on: :collection
      end
    end
  end
  post '/books/save', to: 'books#save', as: 'save'
  post '/author/save', to: 'author#save', as: 'author_save' 
  #root "food_products#index"
end

app/models/food_order.rb
class FoodOrder < ApplicationRecord
  belongs_to :food_product
end

app/controllers/food_orders_controller.rb
class FoodOrdersController < ApplicationController
  before_action :check_user_role,except: [:show_all,:show,:index]
  before_action :get_product,except: [:show_all]
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  layout :determine_layout
  
  def show_all
    @orders = FoodOrder.all
  end

  def index
    @orders=@product.food_orders
  end

  def show
  end

  def new
    @order = @product.food_orders.build
  end

  def edit
  end

  def create
    @order = @product.food_orders.build(order_params)
    if @order.save
      redirect_to '/food_orders'
    else 
      redirect_to '/food_orders/new'
    end
  end
  
  def update
    @order.update(order_params)
    redirect_to food_orders_path
  end

  def order_params
    params.require(:food_order).permit(:food_product_id,:quantity)
  end
  
  def destroy
    @order.destroy
    redirect_to '/food_orders'
  end

  private
  def get_product
    @product=FoodProduct.find(params['food_product_id'])
  end

  def set_order
    @order=@product.food_orders.find(params['id'])
  end

  def check_user_role
    if current_my_user.role=='merchant'
      redirect_to '/home/index'
    end
  end

  def determine_layout
    if current_my_user.role=='admin'
      page_layout="admin"
    else
      page_layout="merchant"
    end
  end
end

app/views/food_orders/_order.html.erb
<%= form_for ([@product,@order]) do |form| %>
  <%= form.text_field :food_product_id, placeholder: 'food product id' %><br/>
  <%= form.text_field :quantity, placeholder: 'quantity' %><br/>
  <%= form.submit %>
<% end %>

app/views/food_orders/edit.html.erb
<h1> Edit Order </h1>
<%= render 'order' %>

app/views/food_orders/index.html.erb
<div class="section" >
  <div class="container">
    <table border='2px'>
      <tr>
        <th>Product Id</th>
        <th>Product Name</th>
        <th>Quantity</th>  
      </tr>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.food_product_id %></td>
          <td><%= order.food_product.name %></td>
          <td><%= order.quantity %></td>
          <% if current_my_user.role!='merchant' %>
          <td><%= link_to "Edit Order", edit_food_product_food_order_path(order.food_product_id,order.id) %></td>
          <% end %>
          <td><%= link_to "Show Order", food_product_food_order_path(order.food_product_id,order.id) %></td>
          <% if current_my_user.role!='merchant' %>
          <td><%= button_to "Destroy Order",food_product_food_order_path(order.food_product_id,order.id),method: 'delete' ,data:{confirm: "are you sure"} %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
  <%= link_to "See all the products", food_products_path %>
</div>

app/views/food_orders/new.html.erb
<h1> Add New Order</h1>
<%= render 'order' %>

app/views/food_orders/show.html.erb
<div class="section" >
  <div class="container">
    <table border='2px'>
      <tr>
        <th>Product Id</th>
        <th>Product Name</th>
        <th>Quantity</th>  
      </tr>
      <tr>
        <td><%= @order.food_product_id %></td>
        <td><%= @order.food_product.name %></td>
        <td><%= @order.quantity %></td>
      </tr>
    </table>
  </div>
</div>

app/views/food_orders/show_all.html.erb
<div class="section" >
  <div class="container">
    <table border='2px'>
      <tr>
        <th>Product Id</th>
        <th>Product Name</th>
        <th>Quantity</th>  
      </tr>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.food_product_id %></td>
          <td><%= order.food_product.name %></td>
          <td><%= order.quantity %></td>
          <% if current_my_user.role!='merchant' %>
          <td><%= link_to "Edit Order", edit_food_product_food_order_path(order.food_product_id,order.id) %></td>
          <% end %>
          <td><%= link_to "Show Order", food_product_food_order_path(order.food_product_id,order.id) %></td>
          <% if current_my_user.role!='merchant' %>
          <td><%= button_to "Destroy Order",food_product_food_order_path(order.food_product_id,order.id),method: 'delete' ,data:{confirm: "are you sure"} %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
  <%= link_to "See all the products", food_products_path %>
</div>