config/routes.rb
Rails.application.routes.draw do
  devise_for :my_users
  get 'home/index'
  root "home#index"
  resources :my_user
  devise_for :views
  resources :products
  resources :students
  resources :faculties
  resources :books
  resources :author
  resources :images
  resources :user001s
  resources :new_users do
    member do
      get :user_profile
      patch :update_profile
      get :change_password
      post :update_password
    end
    collection do
      post :check_password
    end
  end
  resources :food_products do
    resources :food_orders,only: [:index, :show, :edit, :update, :destroy, :new, :create]
  end
  get '/food_orders', to: 'food_orders#show_all'
  
  resources :staffs, only: [:index, :show, :destroy, :update, :edit, :new, :create] do
    collection do
      get :search
    end
  end
  resources :users, only: [:new,:create] do
    collection do
      get :user_profile
    end
  end
  resources :events, only: [:index, :show, :destroy, :update, :edit, :new, :create] do
    member do
      get :user_enrol
    end
    collection do
      get :filter
      get :add_comment
    end
  end
  resources :customers, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :most_booked_order_of_product
      get :most_cancelled_order_of_product
      get :most_sales_product_by_price
      get :most_sales_product_by_quantity
    end
  end
  resources :orders, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :search
      get :filter_data
    end
  end
  resources :shopproducts, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :display_all_products
      get :display_all_products_default
      get :search
    end
  end
  namespace :business do
    resources :buyers, only: [:index, :edit, :create] do
        get 'search', on: :collection
        get 'preview', on: :member
        delete 'delete_customer', on: :member
        patch 'update', on: :member
        get 'new', on: :collection, as: 'new'
    end
  end
  namespace :api do
    namespace :v1 do
      resources :articles do
        get 'search', on: :collection
      end
      resources :article_comments do
        get 'search', on: :collection
      end
    end
  end
  post '/books/save', to: 'books#save', as: 'save'
  post '/author/save', to: 'author#save', as: 'author_save' 
  #root "food_products#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :enrols, dependent: :destroy
  has_many :users, through: :enrols
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user, only: [:index, :show]

  def index
    @events=Event.all.order("date DESC")
  end

  def new
    @event=Event.new
  end
  
  def create
    puts params
    @event=Event.create(event_params)
    if @event.valid?
      redirect_to events_path
    else 
      flash[:errors] = @event.errors.full_messages
      redirect_to new_event_path
    end
  end

  def user_enrol
    user=session[:user_id]
    event_id=params[:id]
    enrolled=Enrol.create(event_id: event_id,user_id: user )
    if enrolled.valid?
      redirect_to events_path
    else
      puts "Cound not enroll in "
    end
  end

  def edit
    @event= Event.find(params['id'])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    if @event.valid?
      redirect_to events_path
    else 
      flash[:errors] = @event.errors.full_messages
      redirect_to new_event_path
    end
  end

  def show
    @event= Event.find(params['id'])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def add_comment
    user=session[:user_id]
    comment=params[:comment]
    event_id=params[:event_id]
    comment_obj=Comment.create(user_id: user,event_id: event_id,comment: comment)
    if comment_obj.valid?
      redirect_to "/events/"+event_id
    else
      redirect_to "/"
    end
  end

  def filter
    if params[:q].blank?
      flash[:errors]=""
      return
    else
      category_id=params[:q][:category_id]
      @events=Event.where(category_id: category_id)
      if @events.blank?
        flash.now[:alert] = "Data not found"
      end  
    end
  end

  private
  def event_params
    params.require(:event).permit(:user_id,:name,:description,:date,:category_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>Edit Your Event Details</h1>
<%= form_for @event do |form| %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>
  <div>
    <%= label_tag(:category_id, "Choose Your Category:") %>
    <%= collection_select(:category_id, :category_id, Category.all, :id, :name) %><br/>
  </div>
  <div>
    <%= form.submit %>
  </div>
<%end%>

app/views/events/filter.html.erb
<h1>Filter page</h1>
<% if flash[:alert] %>
  <div >
    <ul>
        <li style="color:red;"><%= flash[:alert] %></li>
     </ul>
  </div>
<% end %>
<%= form_tag(filter_events_path, :method => "get") do %>
  <%= label_tag(:q, "Choose Your Category:") %>
  <%= collection_select(:q, :category_id, Category.all, :id, :name) %><br/>
  <%= submit_tag("Show") %>
<% end %>
<% if (@events != nil) %>
<table border=" solid 3px ">
  <tr>
  <th>ID</th>
  <th>Event Name</th>
  <th>Event Description</th>
  <th>Event Date</th>
  </tr>
   <% @events.each do |event| %>
    <tr>
      <td><%=event.id %></td>
      <td><%=event.name %></td>
      <td><%=event.description %></td>
      <td><%=event.date %></td>
      <td><%= link_to "Enrol", user_enrol_event_path(id: event.id) %></td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/events/index.html.erb
<h1> All the events </h1>
<table border=" solid 3px ">
  <tr>
  <th>ID</th>
  <th>Event Name</th>
  <th>Event Description</th>
  <th>Event Date</th>
  </tr>
   <% @events.each do |event| %>
    <tr>
      <td><%=event.id %></td>
      <td><%=event.name %></td>
      <td><%=event.description %></td>
      <td><%=event.date %></td>
      <td><%= event.user_id%></td>
      <% if Enrol.where(user_id:@current_user.id,event_id:event.id).blank? %>
        <td><%= link_to "Enrol", user_enrol_event_path(id: event.id) %></td>
      <%else%>
        <td>Enrolled</td>
      <%end%>
      <td><%= link_to "Show", event_path(id: event.id) %></td>
      <% if Event.where(user_id:@current_user.id,id:event.id).blank? %>
        <td>-</td>
      <%else%>
         <td><%= link_to "Update",edit_event_path(id: event.id) %></td>
      <%end%>
      <% if Event.where(user_id:@current_user.id,id:event.id).blank? %>
        <td>-</td>
      <%else%>
         <td><%= button_to "Delete Event",event_path(id: event.id) ,method: 'delete' ,data:{confirm: "are you sure"} %></td>
      <%end%>
    <!--  <td><%= link_to "Show", event_path(id: event.id) %></td>-->
      
    </tr>
  <% end %>
</table>
<br/>
<td><%= link_to "Filter Events", filter_events_path %></td><br/>
<td><%= link_to "Add new event", new_event_path %></td>

app/views/events/new.html.erb
<h1>Add New Event</h1>
<%= form_for @event do |form| %>
  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>
  <div>
    <%= label_tag(:category_id, "Choose Your Category:") %>
    <%= collection_select("event", :category_id, Category.all, :id, :name) %><br/>
  </div>
  <div>
    <%= form.submit %>
  </div>
<%end%>

app/views/events/show.html.erb
<h1>Event</h1>
<div >
  <p>
    <strong>Id:</strong>
    <%= @event.id %>
  </p>
  <p>
    <strong>Event Name:</strong>
    <%= @event.name %>
  </p>
  <p>
    <strong>Event Description:</strong>
    <%= @event.description %>
  </p>
  <p>
    <strong>Event Date:</strong>
    <%= @event.date %>
  </p>
  <p>Add Your Comment</p>
  <%= form_tag(add_comment_events_path, :method => "get") do %>
  <input type='text' name='comment' />
  <input type='hidden' name='event_id' value=<%=@event.id%> >
  <%= submit_tag("Add Comment") %>
  <%end%>
  <p>
    <strong>Comments of all user:</strong>
    <% @event.comments.each do |c| %>
    <p><%= c.user.username %> :<%= c.comment %></p> 
    <hr>
    <%end%>
  </p>
</div>