config/routes.rb
Rails.application.routes.draw do
  devise_for :my_users
  get 'home/index'
  root "home#index"
  resources :my_user
  devise_for :views
  resources :products
  resources :students
  resources :faculties
  resources :books
  resources :author
  resources :images
  resources :user001s
  resources :new_users do
    member do
      get :user_profile
      patch :update_profile
      get :change_password
      post :update_password
    end
    collection do
      post :check_password
    end
  end
  resources :food_products do
    resources :food_orders,only: [:index, :show, :edit, :update, :destroy, :new, :create]
  end
  get '/food_orders', to: 'food_orders#show_all'
  
  resources :staffs, only: [:index, :show, :destroy, :update, :edit, :new, :create] do
    collection do
      get :search
    end
  end
  resources :users, only: [:new,:create] do
    collection do
      get :user_profile
    end
  end
  resources :events, only: [:index, :show, :destroy, :update, :edit, :new, :create] do
    member do
      get :user_enrol
    end
    collection do
      get :filter
      get :add_comment
    end
  end
  resources :customers, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :most_booked_order_of_product
      get :most_cancelled_order_of_product
      get :most_sales_product_by_price
      get :most_sales_product_by_quantity
    end
  end
  resources :orders, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :search
      get :filter_data
    end
  end
  resources :shopproducts, only: [:index, :show, :delete, :update, :edit, :new, :create] do
    collection do
      get :display_all_products
      get :display_all_products_default
      get :search
    end
  end
  namespace :business do
    resources :buyers, only: [:index, :edit, :create] do
        get 'search', on: :collection
        get 'preview', on: :member
        delete 'delete_customer', on: :member
        patch 'update', on: :member
        get 'new', on: :collection, as: 'new'
    end
  end
  namespace :api do
    namespace :v1 do
      resources :articles do
        get 'search', on: :collection
      end
      resources :article_comments do
        get 'search', on: :collection
      end
    end
  end
  post '/books/save', to: 'books#save', as: 'save'
  post '/author/save', to: 'author#save', as: 'author_save' 
  #root "food_products#index"
end

app/models/food_product.rb
class FoodProduct < ApplicationRecord
  has_many :food_orders
  belongs_to :my_user
  validates_presence_of :name,:description,:price,:my_user_id
end

app/controllers/food_products_controller.rb
class FoodProductsController < ApplicationController
  before_action :check_user_role,except: [:index,:show]
  layout :determine_layout 
  
  def index
    @products = current_my_user.food_products.all
  end

  def show
    @products= FoodProduct.find(params['id'])
  end

  def new
    @product = FoodProduct.new
  end

  def edit
    @product= FoodProduct.find(params['id'])
  end

  def create
    @product = FoodProduct.create(product_params)
    if @product.valid?
      redirect_to '/food_products'
    else 
      redirect_to '/food_products/new'
    end
    
  end
  
  def update
    @product = FoodProduct.find(params[:id])
    @product.update(product_params)
    redirect_to food_products_path
  end
  
  def destroy
    @product = FoodProduct.find(params[:id])
    @product.destroy
    redirect_to '/food_products'
  end
  private

  def product_params
    params.require(:food_product).permit(:name,:description,:price,:my_user_id)
  end

  def check_user_role
    if current_my_user.role=='merchant'
      redirect_to '/home/index'
    end
  end

  def determine_layout
    if current_my_user.role=='admin'
      page_layout="admin"
    else
      page_layout="merchant"
    end
  end
end

app/views/food_products/_product.html.erb
<%= form_with model: @product do |form| %>
  <%= form.text_field :name, placeholder: 'Food Product Name' %><br/><br/>
  <%= form.text_field :description, placeholder: 'Food Product Description' %><br/><br/>
  <%= form.number_field :price, placeholder: 'price' %><br/><br/>
  <%= form.text_field :my_user_id,value: current_my_user.id %><br/><br/>
  <%= form.submit %><br/><br/>
<% end %>

app/views/food_products/edit.html.erb
<h1> Edit book </h1>
<%= render 'product' %>

app/views/food_products/index.html.erb
<div class="section" >
  <div class="container">
    <table border='2px'>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>User email</th>
        
      </tr>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.price %></td>
          <td><%=current_my_user.email%></td>
          <% if current_my_user.role!='merchant' %>
            <td><%= link_to "Edit product", edit_food_product_path(id: product.id) %></td>
          <% end %>
          <td><%= link_to "Show product", food_product_path(id: product.id) %></td>
          <% if current_my_user.role!='merchant' %>
          <td><%= link_to "Add order", new_food_product_food_order_path(product.id) %></td>
          <% end %>
          <% if current_my_user.role!='merchant' %>
          <td><%= button_to "Destroy product",food_product_path(id: product.id),method: 'delete' ,data:{confirm: "are you sure"} %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <% if current_my_user.role!='merchant' %>
      <%= link_to "Add a new Product", new_food_product_path %>
    <% end %>
  </div>
</div>

app/views/food_products/new.html.erb
<h1> Add New Product</h1>
<%= render 'product' %>

app/views/food_products/show.html.erb
<div class="section" >
  <div class="container">
    <table border='2px'>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <th>User Email</th>
      </tr>
      <tr>
       <td><%= @products.name %></td>
        <td><%= @products.description %></td>
        <td><%= @products.price %></td>
        <td><%=@products.my_user.email%></td>
        <td><%= link_to "Show all its order", food_product_food_orders_path(@products) %></td>
          
      </tr>
    </table>
    <h3>All the orders of this product are:</h3>
    <% @products.food_orders.each do |order| %>
    <p><b>Product Id:  </b><%= order.food_product_id %>
    <b>Quanitity:  </b><%= order.quantity %></p>
    <% end %>     
  </div>
</div>